WebHard/Controllers/CooperativeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebHard.Controllers
{
    [Authorize]
    public class CooperativeController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult Manpower()
        {
            return View();
        }

        // GET: Cooperative/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cooperative/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cooperative/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cooperative/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cooperative/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cooperative/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult AdminPage() 
        {
            return View();
        }

        public ActionResult ForNewEmployee()
        {
            return View();
        }
        
        public ActionResult DigitalLibrary()
        {
            return View();
        }

    }
}

WebHard/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebHard.Models;
using WebHard.ViewModels;

namespace WebHard.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

WebHard/Controllers/RuralHolidayController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebHard.Models;

namespace WebHard.Controllers
{
    public class RuralHolidayController : Controller
    {
        private readonly ILogger<RuralHolidayController> _logger;

        public RuralHolidayController(ILogger<RuralHolidayController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RuralHolidayOne() 
        {
            return View();
        }
        public IActionResult RuralHolidayTwo()
        {
            return View();
        }
        public IActionResult RuralHolidayThree()
        {
            return View();
        }
        public IActionResult RuralHolidayFour()
        {
            return View();
        }
        public IActionResult RuralHolidayFive()
        {
            return View();
        }
        public IActionResult RuralHolidaySix()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            return View();
        }
        public IActionResult InformationOfCompany()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebHard/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebHard.Models;
using WebHard.ViewModels;

namespace WebHard.Controllers
{
    public class UsersController : Controller
    {
        UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.NewPassword);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.NewPassword);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
    }
}

WebHard/Views/Cooperative/AdminPage.cshtml
@{
    ViewData["Title"] = "Административная страница";
    Layout = "_LayoutCooperative";
}

    <div class="mother-grid" style="padding-bottom: 1000px">
        <div class="container">
            <div class="temp-padd">
                <div class="top-strip">
                    <div class="address">
                        <ul>
                            <li><a href="#"><span class="link"> </span>www.sitename.com</a></li>
                            <li><a href="mailto:example@email.com"><span class="mes"> </span>info@sitename.com</a></li>
                            <li><span class="ph"> </span>+7 777 77 77</li>
                        </ul>
                    </div>
                    <div class="social-icons">
                        <ul>
                            <li><a href="#"> <span class="w-f"> </span></a></li>
                            <li><a href="#"> <span class="w-tw"> </span></a></li>
                            <li><a href="#"> <span class="w-in"> </span></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="title-main">
                    <a><h1>Административная страница</h1></a>

                </div>
                <div class="header">
                    @Html.Partial("~/Views/Menu/CooperativeMenu.cshtml")
                    <div class="clearfix"> </div>
                </div>

                <div class="nuncdig" style="padding: 30px 0 50px 0">

                    
                    <span style="padding-bottom: 15px; padding-right:50px;"><a asp-controller="Users" asp-action="Index">Редактирование/добавление пользователей</a></span>

                    <a asp-controller="Roles" asp-action="Index">Управление/добавление ролей</a>


                </div>
            </div>
        </div>
    </div>

WebHard/Views/Cooperative/DigitalLibrary.cshtml
@{
    ViewData["Title"] = "Электронная библиотека";
    Layout = "_LayoutCooperative";
}

<div class="mother-grid" style="padding-bottom: 1000px">
    <div class="container">
        <div class="temp-padd">
            <div class="top-strip">
                <div class="address">
                    <ul>
                        <li><a href="#"><span class="link"> </span>www.Матвеев.com</a></li>
                        <li><a href="mailto:example@email.com"><span class="mes"> </span>info@sitename.com</a></li>
                        <li><span class="ph"> </span>+7 777 77 77</li>
                    </ul>
                </div>
                <div class="social-icons">
                    <ul>
                        <li><a href="#"> <span class="w-f"> </span></a></li>
                        <li><a href="#"> <span class="w-tw"> </span></a></li>
                        <li><a href="#"> <span class="w-in"> </span></a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="title-main">
                <a><h1>Электронная библиотека</h1></a>
                

            </div>
            <div class="header">
                @Html.Partial("~/Views/Menu/CooperativeMenu.cshtml")
                <div class="clearfix"> </div>
            </div>

            <div class="nuncdig" style="padding: 30px 0 50px 0">

                <a download href="~/Content/Books/selhoz.pdf">Глобальные проекты и субсидии</a><br /><br />

                <a download href="~/Content/Books/metodichka-final.pdf">Сельский туризм как средство развития сельских территорий</a><br /><br />

                <a download href="~/Content/Books/selskiy_turizm.pdf">Сельский туризм: опыт, проблемы, перспективы развития в России</a><br /><br />

                <a download href="~/Content/Books/tkodeksrf.pdf">Трудовой кодекс РФ</a><br /><br />



            </div>
        </div>
    </div>
</div>

WebHard/Views/Cooperative/ForNewEmployee.cshtml
@{
 Layout = "_LayoutCooperative";
}

<div class="mother-grid" style="padding-bottom: 1000px">
    <div class="container">
        <div class="temp-padd">
            <div class="top-strip">
                <div class="address">
                    <ul>
                        <li><a href="#"><span class="link"> </span>www.Матвеев.com</a></li>
                        <li><a href="mailto:example@email.com"><span class="mes"> </span>info@sitename.com</a></li>
                        <li><span class="ph"> </span>+7 777 77 77</li>
                    </ul>
                </div>
                <div class="social-icons">
                    <ul>
                        <li><a href="#"> <span class="w-f"> </span></a></li>
                        <li><a href="#"> <span class="w-tw"> </span></a></li>
                        <li><a href="#"> <span class="w-in"> </span></a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="title-main">
                <a><h1>Новым сотрудникам</h1></a>


            </div>
            <div class="header">
                @Html.Partial("~/Views/Menu/CooperativeMenu.cshtml")
                <div class="clearfix"> </div>
            </div>

            <div class="nuncdig" style="padding: 30px 0 50px 0">
                Телефон менеджера по персоналу: +7 777 77 77<br /><br />
                Телефон бухгалтерии: + 3 333 33 33<br /><br />
                Телфон для пропусков: +2 222 22 22<br /><br />
                <a download href="~/Content/Books/ustav_6.pdf">Устав</a><br /><br />

            </div>
        </div>
    </div>
</div>

WebHard/Views/Cooperative/Index.cshtml
@model CooperativeModel

@{
    Layout = "_LayoutCooperative";
}
<div class="mother-grid">
    <div class="container">
        <div class="temp-padd">
            <div class="top-strip">
                <div class="address">
                    <ul>
                        <li><a href="#"><span class="link"> </span>www.Матвеев.com</a></li>
                        <li><a href="mailto:example@email.com"><span class="mes"> </span>инфо@sitename.com</a></li>
                        <li><span class="ph"> </span>+7 777 77 77</li>
                    </ul>
                </div>
                <div class="social-icons">
                    <ul>
                        <li><a href="#"> <span class="w-f"> </span></a></li>
                        <li><a href="#"> <span class="w-tw"> </span></a></li>
                        <li><a href="#"> <span class="w-in"> </span></a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="title-main">
                <a ><h1>Новости компании и многое другое</h1></a>

            </div>
            <div class="header">
                @Html.Partial("~/Views/Menu/CooperativeMenu.cshtml")
                <div class="clearfix"> </div>
            </div>
            <div class="banner">
                <img src="~/Content/images/cooperativeImg/logo.png" alt="" />
                <h3>Новостная страница</h3>
                <h2>Подписывайтесь на наш телеграм!</h2>
                <div class="banner-button">
                    <a href="#">Подписаться</a>
                </div>
            </div>
            <div class="nuncdig">
                <div class="nuncdig-main">
                    <div class="nunc-top">
                        <h3>Объявления для сотрудников</h3>
                        <p></p>
                    </div>
                    <div class="nunc-bott">
                        <div class="col-md-4 nunc-bott-grid">
                            <div class="headind-text">
                                <h3>Внимане, сотрудники!</h3>
                                <h4></h4>
                            </div>
                            <p>Обратиться в медицинский пункт для проведения вакцинации от энцефалита!!!</p>
                            <div class="nunc-bwn">
                                @*<a href="#">Более</a>*@
                            </div>
                        </div>
                        <div class="col-md-4 nunc-bott-grid">
                            <div class="headind-text">
                                <h3>ИНН</h3>
                                <h4></h4>
                            </div>
                            <p>Прислать в кадровый отдел идентификационный номер налогоплательщика!</p>
                            <div class="nunc-bwn">
                                @*<a href="#">Более</a>*@
                            </div>
                        </div>
                        <div class="col-md-4 nunc-bott-grid">
                            <div class="headind-text">
                                <h3>Внимание администрация!</h3>
                                <h4></h4>
                            </div>
                            <p>Связаться с заместителем главного директора!</p>
                            <div class="nunc-bwn">
                                @*<a href="#">Более</a>*@
                            </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
            </div>
            <script src="@Url.Content("~/js/CooperativeJs/responsiveslides.min.js")" type="text/javascript"></script>
            <script type="text/javascript">
                (function () {
                    $("#slider4").responsiveSlides({
                        auto: true,
                        pager: true,
                        nav: true,
                        speed: 500,
                        namespace: "callbacks",
                        before: function () {
                            $('.events').append("<li>before event fired.</li>");
                        },
                        after: function () {
                            $('.events').append("<li>after event fired.</li>");
                        }
                    });

                });</script>
            <div class="clearfix"> </div>
            <div class="info-grid">
                <div class="info-grid-main">
                    <div class="col-md-6 info-grid-left">
                        <div class="info-left-top">
                            <div class="info-heading">
                                <h3>Бюджетные счета соберут в единую систему</h3>
                                <p>Узнать по ссылке</p>
                            </div>
                            <div class="info-para">
                                <p> </p>
                                <div class="info-bwn">
                                    <a href="https://rg.ru/2019/12/30/chto-izmenitsia-v-zhizni-rossiian-v-2020-godu.html">Более</a>
                                </div>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                        <div class="info-left-bottom">
                            <div class="info-heading">
                                <h3>Криминальную статистику станут публиковать в сети</h3>
                                <p>Узнать по ссылке</p>
                            </div>
                            <div class="info-para">
                                <p></p>
                                <div class="info-bwn">
                                    <a href="https://rg.ru/2019/12/30/chto-izmenitsia-v-zhizni-rossiian-v-2020-godu.html">Более</a>
                                </div>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </div>
                    <div class="col-md-6 info-grid-right">
                        <div class="menu_vertical">
                            <section class="accordation_menu">
                                <div>
                                    <input id="label-1" name="lida" type="radio" checked />
                                    <label for="label-1" id="item1"><i class="ferme"> </i><span class="m_5">Нововведения для автомобилистов</span><i class="icon-plus-sign i-right1"></i><i class="icon-minus-sign i-right2"></i></label>
                                    <div class="content1" id="a1">
                                        <ul class="news_list">
                                            <li class="sml-img"> </li>
                                            <li class="date_desc">
                                                <h3></h3>
                                                <p>
                                                    Из автосалонов машины начнут выезжать с номерами. Сейчас при покупке нового автомобиля дается 10 дней, чтобы поставить его на учет. Все это время можно ездить без номерных знаков.

                                                </p>
                                            </li>
                                            <div class="clearfix"> </div>
                                        </ul>
                                    </div>
                                </div>
                                <div>
                                    <input id="label-2" name="lida" type="radio" />
                                    <label for="label-2" id="item2"><i class="icon-leaf" id="i2"></i>Пенсии, МРОТ и налоги<i class="icon-plus-sign i-right1"></i><i class="icon-minus-sign i-right2"></i></label>
                                    <div class="content1" id="a2">
                                        <ul class="news_list">
                                            <li class="sml-img"> </li>
                                            <li class="date_desc">
                                                <h3></h3>
                                                <p>С 1 января неработающие пенсионеры начнут получать на 6,6% больше. Государственное пенсионное обеспечение, в том числе социальные пенсии, увеличится на 7%, но только с 1 апреля.</p>
                                            </li>
                                            <div class="clearfix"> </div>
                                        </ul>
                                    </div>
                                </div>
                                <div>
                                    <input id="label-3" name="lida" type="radio" />
                                    <label for="label-3" id="item3"><i class="icon-trophy" id="i3"></i>ЖКХ и общественный транспорт<i class="icon-plus-sign i-right1"></i><i class="icon-minus-sign i-right2"></i></label>
                                    <div class="content1" id="a3">
                                        <ul class="news_list">
                                            <li class="sml-img"> </li>
                                            <li class="date_desc">
                                                <h3></h3>
                                                <p>
                                                    В 2019 году индексация жилищно-коммунальных тарифов проходила в два этапа — в январе и июле. В 2020 году она пройдет во втором полугодии. С 1 июня 2020 года оплата услуг ЖКХ в целом по России вырастет на 4%.
                                                </p>
                                            </li>
                                            <div class="clearfix"> </div>
                                        </ul>
                                    </div>
                                </div>
                                <div>
                                    <input id="label-4" name="lida" type="radio" />
                                    <label for="label-4" id="item4"><i class="icon-trophy" id="i4"></i>Выплаты родителям<i class="icon-plus-sign i-right1"></i><i class="icon-minus-sign i-right2"></i></label>
                                    <div class="content1" id="a4">
                                        <ul class="news_list">
                                            <li class="sml-img"> </li>
                                            <li style="padding-bottom:20px" class="date_desc">
                                                <h3></h3>
                                                <p>
                                                    В прошлое уходят мизерные 50-рублевые выплаты по уходу за ребенком от полутора до трех лет.
                                                </p>
                                            </li>
                                            <div class="clearfix"> </div>
                                        </ul>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="footer-main">
                @*<div class="footer-top">
                    <div class="col-md-4 footer-grid">
                        <img src="~/Content/images/cooperativeImg/ftr-fa.png" alt="" />
                        <a href="#"><h3>Фэйсбук</h3></a>
                        <p>текст</p>
                        <h4>текст</h4>
                    </div>
                    <div class="col-md-4 footer-grid">
                        <img src="~/Content/images/cooperativeImg/tw.png" alt="" />
                        <a href="#"><h3>Твиттер</h3></a>
                        <p>текст</p>
                        <h4>текст</h4>
                    </div>
                    <div class="col-md-4 footer-grid">
                        <img src="~/Content/images/cooperativeImg/drib.png" alt="" />
                        <a href="#"><h3>текст</h3></a>
                        <p>текст</p>
                        <h4>текст</h4>
                    </div>
                    <div class="clearfix"> </div>
                </div>*@
                <div class="footer-bottom">
                    <p> @Html.ActionLink("Здоровый отдых", "Index", "RuralHoliday")</p>
                </div>
            </div>
        </div>
    </div>
</div>

WebHard/Views/Cooperative/Manpower.cshtml
@model ManpowerModel