WebHard/Controllers/CooperativeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebHard.Controllers
{
    [Authorize]
    public class CooperativeController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult Manpower()
        {
            return View();
        }

        // GET: Cooperative/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cooperative/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cooperative/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cooperative/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cooperative/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cooperative/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult AdminPage() 
        {
            return View();
        }

        public ActionResult ForNewEmployee()
        {
            return View();
        }
        
        public ActionResult DigitalLibrary()
        {
            return View();
        }

    }
}

WebHard/Controllers/RuralHolidayController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebHard.Models;

namespace WebHard.Controllers
{
    public class RuralHolidayController : Controller
    {
        private readonly ILogger<RuralHolidayController> _logger;

        public RuralHolidayController(ILogger<RuralHolidayController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RuralHolidayOne() 
        {
            return View();
        }
        public IActionResult RuralHolidayTwo()
        {
            return View();
        }
        public IActionResult RuralHolidayThree()
        {
            return View();
        }
        public IActionResult RuralHolidayFour()
        {
            return View();
        }
        public IActionResult RuralHolidayFive()
        {
            return View();
        }
        public IActionResult RuralHolidaySix()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            return View();
        }
        public IActionResult InformationOfCompany()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebHard/Views/RuralHoliday/Contacts.cshtml
@{
    ViewData["Title"] = "Contacts";
    Layout = "_LayoutVisiting";
}


<div class="wrapper style1">

    <div id="header" class="skel-panels-fixed">
        <div id="logo">
            <h1><a asp-controller="RuralHoliday" asp-action="Index">Здоровый отдых</a></h1>
            <span class="tag">by X Банк</span>
        </div>
        <nav id="nav">
            <ul>
                <li><a asp-controller="RuralHoliday" asp-action="Index">На главную страницу</a></li>
            </ul>
        </nav>
    </div>

    <div id="page" class="container">
        <section>
            <header class="major">
                <h2>Контакты</h2>
                <span class="byline">Информация для регистрации и общения с компанией</span>
            </header>
            <p>Добро пожаловать на наш сайт!</p>
            <p>Для регистрации и вопрос можете обратиться на нашуй почту otdyh@pochta.ru или по номеру +7 777 77 77</p>
            <p>Так же для связи можете использовать форму ниже</p>
        </section>
    </div>
</div>

<div id="footer" class="wrapper style2">
    <div class="container">
        <section>
            <header class="major">
                <h2>Напишите нам письмо</h2>
                <span class="byline">Мы ответим Вам на любой вопрос и зарегистрируем!</span>
            </header>
            <form method="post" action="#">
                <div class="row half">
                    <div class="12u">
                        <input class="text" type="text" name="name" id="name" placeholder="Имя" />
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <input class="text" type="text" name="email" id="email" placeholder="Ваша почта" />
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <textarea name="message" id="message" placeholder="Сообщение"></textarea>
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <ul class="actions">
                            <li>
                                <input type="submit" value="Отправить сообщение" class="button alt" />
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
<div id="copyright">
    <div class="container">
        <ul class="icons">
            <li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
            <li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
            <li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
        </ul>
    </div>
</div>

WebHard/Views/RuralHoliday/Index.cshtml
@model VisitingModel
@{
    ViewData["Title"] = "HomePage";
    Layout = "_LayoutVisiting";
}

        <div class="wrapper style1">

            <div id="header" class="skel-panels-fixed">
                <div id="logo">
                    <h1><a asp-controller="RuralHoliday" asp-action="Index">Здоровый отдых</a></h1>
                    <span class="tag">by X Банк</span>
                </div>
                <nav id="nav">
                    <ul>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li style="padding: 0 0 0 0;">
                                @User.Identity.Name
                            </li>
                            <li style="padding: 0 0 0 0;">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input style="font-size:80%;" type="submit" value="Выход" />
                                </form>
                            </li>

                            <li><a>@Html.ActionLink("Корпоративный сайт", "Index", "Cooperative")</a></li>
                        }
                        else
                        {
                            <li>
                                <a asp-controller="Account" asp-action="Login">Вход для сотрудников компании</a>
                                @*<a asp-controller="Account" asp-action="Register">Регистрация</a>*@
                            </li>
                        }

                        <li><a asp-controller="RuralHoliday" asp-action="Contacts">Контакты</a></li>
                    </ul>
                </nav>
            </div>

            <div id="banner" class="container">
                <section style="color: white">
                    <p>Приветствуем Вас на сайте нашей компании сельского туризма <strong>"Здоровый отдых"</strong></p>
                    <p>Для просмотра информации о нашей компании можете здесь:</p>
                    <a class="button medium" asp-controller="RuralHoliday" asp-action="InformationOfCompany">Просмотреть</a>
                    <p>А так же ознакомьтесь с нашими услугами</p>
                </section>
            </div>

            <!-- Extra -->
            <div id="extra">
                <div class="container">
                    <div class="row no-collapse-1">
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidayOne" class="image featured"><img src="~/Content/images/visitingImg/pic01.jpg" alt=""></a>
                            <div class="box">
                                <p>Избы, пруд, места для жилья и отдыха!</p>
                                <a class="button" asp-controller="RuralHoliday" asp-action="RuralHolidayOne">Просмотреть</a>
                            </div>
                        </section>
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidayTwo" class="image featured"><img height="244" src="~/Content/images/visitingImg/pic02.jpg" alt=""></a>
                            <div class="box">
                                <p>У нас уникальная возможность заняться кузнечным и декоративным делом!</p>
                                <a asp-controller="RuralHoliday" asp-action="RuralHolidayTwo" class="button">Просмотреть</a>
                            </div>
                        </section>
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidayThree" class="image featured"><img src="~/Content/images/visitingImg/pic03.jpg" alt=""></a>
                            <div class="box">
                                <p>Баня поможет вам расслабить тело и укрепить дух! А коптильная наполнена изысканным деликатесом!</p>
                                <a asp-controller="RuralHoliday" asp-action="RuralHolidayThree" class="button">Просмотреть</a>
                            </div>
                        </section>
                    </div>
                    <div class="row no-collapse-1">
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidayFour" class="image featured"><img src="~/Content/images/visitingImg/pic04.jpg" alt=""></a>
                            <div class="box">
                                <p>Посетите наш музей посвященный древней Руси!</p>
                                <a asp-controller="RuralHoliday" asp-action="RuralHolidayFour" class="button">Просмотреть</a>
                            </div>
                        </section>
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidayFive" class="image featured"><img src="~/Content/images/visitingImg/pic05.jpg" alt=""></a>
                            <div class="box">
                                <p>Приглашаем на празднование, посвященное 23 февраля! Будут организованы стрельбища и многое другое!</p>
                                <a asp-controller="RuralHoliday" asp-action="RuralHolidayFive" class="button">Просмотреть</a>
                            </div>
                        </section>
                        <section class="4u">
                            <a asp-controller="RuralHoliday" asp-action="RuralHolidaySix" class="image featured"><img src="~/Content/images/visitingImg/pic06.jpg" alt=""></a>
                            <div class="box">
                                <p>Зоопарк с чудными зверушками!</p>
                                <a asp-controller="RuralHoliday" asp-action="RuralHolidaySix" class="button">Просмотреть</a>
                            </div>
                        </section>
                    </div>
                </div>
            </div>

            <div id="main">
                <div class="container">
                    <div class="row">

                        <div class="6u">
                            <section>
                                <ul class="style">
                                    <li class="fa fa-wrench">
                                        <h3>Персонал</h3>
                                        <span>В нашей компании работают наилучшие профессионалы</span>
                                    </li>
                                    <li class="fa fa-leaf">
                                        <h3>Экологичность</h3>
                                        <span>Чистая природа даст вам все необходимое</span>
                                    </li>
                                </ul>
                            </section>
                        </div>
                        <div class="6u">
                            <section>
                                <ul class="style">
                                    <li class="fa fa-cogs">
                                        <h3>Современность</h3>
                                        <span>Современный и технологичный подход к природе и людям</span>
                                    </li>
                                    <li class="fa fa-road">
                                        <h3>Расположение</h3>
                                        <span>Наша компания находится 300 км от МКАД</span>
                                    </li>
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div id="footer" class="wrapper style2">
            <div class="container">
                <section>
                    <header class="major">
                        <h2>Напишите нам письмо</h2>
                        <span class="byline">Мы ответим Вам на любой вопрос и зарегистрируем!</span>
                    </header>
                    <form method="post" action="#">
                        <div class="row half">
                            <div class="12u">
                                <input class="text" type="text" name="name" id="name" placeholder="Имя" />
                            </div>
                        </div>
                        <div class="row half">
                            <div class="12u">
                                <input class="text" type="text" name="email" id="email" placeholder="Ваша почта" />
                            </div>
                        </div>
                        <div class="row half">
                            <div class="12u">
                                <textarea name="message" id="message" placeholder="Сообщение"></textarea>
                            </div>
                        </div>
                        <div class="row half">
                            <div class="12u">
                                <ul class="actions">
                                    <li>
                                        <input type="submit" value="Отправить сообщение" class="button alt" />
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>

        <div id="copyright">
            <div class="container">
                <div class="copyright">
                    <p>Подпишись на нас</p>
                    <ul class="icons">
                        <li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
                        <li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
                        <li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
                    </ul>
                </div>
            </div>
        </div>

WebHard/Views/RuralHoliday/InformationOfCompany.cshtml
@{
    ViewData["Title"] = "InformationOfCompany";
    Layout = "_LayoutVisiting";
}


<div class="wrapper style1">

    <div id="header" class="skel-panels-fixed">
        <div id="logo">
            <h1><a asp-controller="RuralHoliday" asp-action="Index">Здоровый отдых</a></h1>
            <span class="tag">by X Банк</span>
        </div>
        <nav id="nav">
            <ul>
                <li><a asp-controller="RuralHoliday" asp-action="Index">На главную страницу</a></li>

                <li><a asp-controller="RuralHoliday" asp-action="Contacts">Контакты</a></li>
            </ul>
        </nav>
    </div>

    <div id="page" class="container">
        <section>
            <header class="major">
                <h2>О нашей компании "Здоровый отдых"</h2>
                <span class="byline">Наша компания основана в 2020 году баком X Банк</span>
                <p>Дорогие посетители добро пожадывать на наш сайт!</p>
                <p>Мы хоти вам предложить необходимый отдых в современных рамках города.</p>
                
            </header></section>
    </div>
</div>

<div id="footer" class="wrapper style2">
    <div class="container">
        <section>
            <header class="major">
                <h2>Напишите нам письмо</h2>
                <span class="byline">Мы ответим Вам на любой вопрос и зарегистрируем!</span>
            </header>
            <form method="post" action="#">
                <div class="row half">
                    <div class="12u">
                        <input class="text" type="text" name="name" id="name" placeholder="Имя" />
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <input class="text" type="text" name="email" id="email" placeholder="Ваша почта" />
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <textarea name="message" id="message" placeholder="Сообщение"></textarea>
                    </div>
                </div>
                <div class="row half">
                    <div class="12u">
                        <ul class="actions">
                            <li>
                                <input type="submit" value="Отправить сообщение" class="button alt" />
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
<div id="copyright">
    <div class="container">
        <ul class="icons">
            <li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
            <li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
            <li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
        </ul>
    </div>
</div>

WebHard/Views/RuralHoliday/RuralHolidayFive.cshtml
@{
    ViewData["Title"] = "RuralHolidayFive";
    Layout = "_LayoutVisiting";
}

<link href="@Url.Content("~/css/SlideShowCss.css")" rel="stylesheet" type="text/css" />

<div class="wrapper style1">
    <div id="header" class="skel-panels-fixed">
        <div id="logo">
            <h1><a asp-controller="RuralHoliday" asp-action="Index">Здоровый отдых</a></h1>
            <span class="tag">by X Банк</span>
        </div>
        <nav id="nav">
            <ul>
                <li><a asp-controller="RuralHoliday" asp-action="Index">На главную страницу</a></li>
                <li><a asp-controller="RuralHoliday" asp-action="Contacts">Контакты</a></li>
            </ul>
        </nav>
    </div>
    <div id="page" class="container">
        <div class="row">

            <div id="sidebar" class="4u">
                <section>
                    <header class="major">
                        <h2>Меню сайта</h2>
                    </header>
                    <div class="row half">
                        <section class="6u">
                            <ul class="default">
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidayOne">Дома отдыхающих</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidayTwo">Кузнечное и декоративное дело</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidayThree">Баня</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidayFour">Музей</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidayFive">Отмечаем праздники</a></li>
                            </ul>
                        </section>
                        <section class="6u">
                            <ul class="default small">
                                <li><a asp-controller="RuralHoliday" asp-action="RuralHolidaySix">Мини зоопарк</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="Contacts">Контакты</a></li>
                                <li><a asp-controller="RuralHoliday" asp-action="InformationOfCompany">О нас</a></li>
                            </ul>
                        </section>
                    </div>
                </section>
                @*<section>
                <header class="major">
                    <h2></h2>
                </header>
                <ul class="default">
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                    <li><a href="#"></a></li>
                </ul>
            </section>*@
            </div>

            <div id="content" class="8u skel-cell-important">

                <section>
                    <header class="major">
                        <h2>Приезжайте на праздник 23 февраля</h2>
                        <span class="byline"></span>
                    </header>
                    <div class="slideshow-container">
                        <div class="mySlides fade">
                            <div class="numbertext">1 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o1.jpg" style="width:100%">
                        </div>

                        <div class="mySlides fade">
                            <div class="numbertext">2 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o2.jpg" style="width:100%">
                        </div>

                        <div class="mySlides fade">
                            <div class="numbertext">3 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o3.jpg" style="width:100%">
                        </div>
                        <div class="mySlides fade">
                            <div class="numbertext">4 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o4.jpg" style="width:100%">
                        </div>
                        <div class="mySlides fade">
                            <div class="numbertext">5 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o5.jpg" style="width:100%">
                        </div>
                        <div class="mySlides fade">
                            <div class="numbertext">6 / 6</div>
                            <img src="~/Content/images/visitingImg/holidays/o6.jpg" style="width:100%">
                        </div>

                        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                        <a class="next" onclick="plusSlides(1)">&#10095;</a>
                    </div>
                    <br>
                    <div style="text-align:center">
                        <span class="dot" onclick="currentSlide(1)"></span>
                        <span class="dot" onclick="currentSlide(2)"></span>
                        <span class="dot" onclick="currentSlide(3)"></span>
                        <span class="dot" onclick="currentSlide(4)"></span>
                        <span class="dot" onclick="currentSlide(5)"></span>
                        <span class="dot" onclick="currentSlide(6)"></span>
                    </div>

                </section>
                23 февраля в нашей стране отмечается День воинской славы России — День защитника Отечества. Эта дата установлена Федеральным законом «О днях воинской славы и памятных датах России», принятым Государственной думой и подписанным президентом РФ Б.Ельциным 13 марта 1995 года.

            </div>

        </div>
    </div>

</div>

<div id="copyright">
    <div class="container">
        <ul class="icons">
            <li><a href="#" class="fa fa-facebook"><span>Facebook</span></a></li>
            <li><a href="#" class="fa fa-twitter"><span>Twitter</span></a></li>
            <li><a href="#" class="fa fa-google-plus"><span>Google+</span></a></li>
        </ul>
    </div>
</div>
<script type="text/javascript">

        var slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function currentSlide(n) {
            showSlides(slideIndex = n);
        }


        function showSlides(n) {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("dot");
            if (n > slides.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = slides.length }
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" active", "");
            }
            slides[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " active";
        }
</script>